# Dependencies
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:     true

# Permalinks
permalink:      pretty

baseurl:        "https://mattkevan.github.io/Jekyll-simple-docs"
url:            ""
encoding:       UTF-8

sass:
  sass_dir: css

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

# Social
title:              Simple docs
description:        "Am easy-to-use Bootstrap-based documentation site."
twitter:            
authors:            ""

# Custom variables
logo:           "logo.svg"
repo:           "https://github.com/MattKevan/Jekyll-simple-docs"
slack:          "https://slack.com"
blog:           ""
website:        "https://www.kevan.tv"

toc:
  min_level:        2
  max_level:        4

