# Dependencies
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:     true

# Permalinks
permalink:      pretty

baseurl:        ""
url:            ""
encoding:       UTF-8

sass:
  sass_dir: css

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc

# Social
title:              Simple Docs
description:        "Simple Bootstrap-based documentation site"
twitter:            
authors:            ""

# Custom variables
logo:           "logo.svg"
repo:           "https://github.com/mattkevan"
slack:          "https://slack.com"
blog:           ""
website:        "https://www.kevan.tv"

toc:
  min_level:        2
  max_level:        4
