backend:
  name: github
  repo: MattKevan/wiki
  

media_folder: "assets/images" # Folder where user uploaded files should go

publish_mode: editorial_workflow # Enable drafts

collections: # A list of collections the CMS should be able to edit
  # POSTS
  - name: "document" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Document" # Used in the UI, ie.: "New Post"
    folder: "_documents" # The path to the folder where the documents are stored
    sort: "title:asc"
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "docs"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Category", name: "category", widget: "string", required: true}
      - {label: "Body", name: "body", widget: "markdown", required: false}